ci: Run sdk and api tests in ci
This adds new makefile targets and configuration to run the tests in the
api and sdk modules. These do not run by default since `go test ./...`
does not cross module boundaries.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -179,6 +179,155 @@ jobs:
         name: Save package cache
         paths:
         - .buildcache/packages/store
+  test-api:
+    machine:
+      image: ubuntu-2004:202107-02
+    resource_class: medium
+    working_directory: ~/boundary
+    steps:
+    - checkout
+    - run:
+        command: |
+          make install-go
+          source ~/.bashrc
+          echo 'export GOROOT=$GOROOT' >> "$BASH_ENV"
+          echo 'export GOPATH=$GOPATH' >> "$BASH_ENV"
+          echo 'export PATH=$PATH' >> "$BASH_ENV"
+          echo "$ go version"
+          go version
+        name: Install go
+    - run:
+        command: |
+          make test-api
+        name: Run API Tests
+        no_output_timeout: 15m
+    - run:
+        command: |
+          echo 'export SLACK_BUILD_STATUS="fail"' >> $BASH_ENV
+        name: Slack - Setting Failure Condition
+        when: on_fail
+    - run:
+        command: |
+          echo 'export SLACK_BUILD_STATUS="success"' >> $BASH_ENV
+        name: Slack - Setting Success Condition
+        when: on_success
+    - run:
+        command: |
+          if [ ! -x /bin/bash ]; then
+            echo Bash not installed.
+            exit 1
+          fi
+        name: Provide error if non-bash shell
+    - run:
+        command: |
+          current_branch_in_filter=false
+
+          IFS="," read -ra BRANCH_FILTERS <<< "master"
+
+          for i in "${BRANCH_FILTERS[@]}"; do
+            if [ "${i}" == "${CIRCLE_BRANCH}" ]; then
+              current_branch_in_filter=true
+            fi
+          done
+
+          if [ "x" == "xmaster" ] || [ "$current_branch_in_filter" = true ]; then
+            # Provide error if no webhook is set and error. Otherwise continue
+            if [ -z "webhook" ]; then
+              echo "NO SLACK WEBHOOK SET"
+              echo "Please input your SLACK_WEBHOOK value either in the settings for this project, or as a parameter for this orb."
+              exit 1
+            else
+              #Create Members string
+              if [ -n "" ]; then
+                IFS="," read -ra SLACK_MEMBERS <<< ""
+                for i in "${SLACK_MEMBERS[@]}"; do
+                  if [ $(echo ${i} | head -c 1) == "S" ]; then
+                    SLACK_MENTIONS="${SLACK_MENTIONS}<!subteam^${i}> "
+                  elif echo ${i} | grep -E "^(here|channel|everyone)$" > /dev/null; then
+                    SLACK_MENTIONS="${SLACK_MENTIONS}<!${i}> "
+                  else
+                    SLACK_MENTIONS="${SLACK_MENTIONS}<@${i}> "
+                  fi
+                done
+              fi
+              #If successful
+              if [ "$SLACK_BUILD_STATUS" = "success" ]; then
+                #Skip if fail_only
+                if [ true = true ]; then
+                  echo "The job completed successfully"
+                  echo '"fail_only" is set to "true". No Slack notification sent.'
+                else
+                  curl -X POST -H 'Content-type: application/json' \
+                    --data "{ \
+                              \"attachments\": [ \
+                                { \
+                                  \"fallback\": \":tada: A $CIRCLE_JOB job has succeeded!\", \
+                                  \"text\": \":tada: A $CIRCLE_JOB job has succeeded! $SLACK_MENTIONS\", \
+                                  \"fields\": [ \
+                                    { \
+                                      \"title\": \"Project\", \
+                                      \"value\": \"$CIRCLE_PROJECT_REPONAME\", \
+                                      \"short\": true \
+                                    }, \
+                                    { \
+                                      \"title\": \"Job Number\", \
+                                      \"value\": \"$CIRCLE_BUILD_NUM\", \
+                                      \"short\": true \
+                                    } \
+                                  ], \
+                                  \"actions\": [ \
+                                    { \
+                                      \"type\": \"button\", \
+                                      \"text\": \"Visit Job\", \
+                                      \"url\": \"$CIRCLE_BUILD_URL\" \
+                                    } \
+                                  ], \
+                                  \"color\": \"#1CBF43\" \
+                                } \
+                              ] \
+                            } " webhook
+                  echo "Job completed successfully. Alert sent."
+                fi
+              else
+                #If Failed
+                curl -X POST -H 'Content-type: application/json' \
+                  --data "{ \
+                    \"attachments\": [ \
+                      { \
+                        \"fallback\": \":red_circle: A $CIRCLE_JOB job has failed!\", \
+                        \"text\": \":red_circle: A $CIRCLE_JOB job has failed! $SLACK_MENTIONS\", \
+                        \"fields\": [ \
+                          { \
+                            \"title\": \"Project\", \
+                            \"value\": \"$CIRCLE_PROJECT_REPONAME\", \
+                            \"short\": true \
+                          }, \
+                          { \
+                            \"title\": \"Job Number\", \
+                            \"value\": \"$CIRCLE_BUILD_NUM\", \
+                            \"short\": true \
+                          } \
+                        ], \
+                        \"actions\": [ \
+                          { \
+                            \"type\": \"button\", \
+                            \"text\": \"Visit Job\", \
+                            \"url\": \"$CIRCLE_BUILD_URL\" \
+                          } \
+                        ], \
+                        \"color\": \"#ed5c5c\" \
+                      } \
+                    ] \
+                  } " webhook
+                echo "Job failed. Alert sent."
+              fi
+            fi
+          else
+            echo "Current branch is not included in only_for_branches filter; no status alert will be sent"
+          fi
+        name: Slack - Sending Status Alert
+        shell: /bin/bash
+        when: always
   darwin_arm64_package:
     docker:
     - image: docker.mirror.hashicorp.services/circleci/buildpack-deps
@@ -591,6 +740,155 @@ jobs:
         name: Save package cache
         paths:
         - .buildcache/packages/store
+  test-sdk:
+    machine:
+      image: ubuntu-2004:202107-02
+    resource_class: medium
+    working_directory: ~/boundary
+    steps:
+    - checkout
+    - run:
+        command: |
+          make install-go
+          source ~/.bashrc
+          echo 'export GOROOT=$GOROOT' >> "$BASH_ENV"
+          echo 'export GOPATH=$GOPATH' >> "$BASH_ENV"
+          echo 'export PATH=$PATH' >> "$BASH_ENV"
+          echo "$ go version"
+          go version
+        name: Install go
+    - run:
+        command: |
+          make test-sdk
+        name: Run SDK Tests
+        no_output_timeout: 15m
+    - run:
+        command: |
+          echo 'export SLACK_BUILD_STATUS="fail"' >> $BASH_ENV
+        name: Slack - Setting Failure Condition
+        when: on_fail
+    - run:
+        command: |
+          echo 'export SLACK_BUILD_STATUS="success"' >> $BASH_ENV
+        name: Slack - Setting Success Condition
+        when: on_success
+    - run:
+        command: |
+          if [ ! -x /bin/bash ]; then
+            echo Bash not installed.
+            exit 1
+          fi
+        name: Provide error if non-bash shell
+    - run:
+        command: |
+          current_branch_in_filter=false
+
+          IFS="," read -ra BRANCH_FILTERS <<< "master"
+
+          for i in "${BRANCH_FILTERS[@]}"; do
+            if [ "${i}" == "${CIRCLE_BRANCH}" ]; then
+              current_branch_in_filter=true
+            fi
+          done
+
+          if [ "x" == "xmaster" ] || [ "$current_branch_in_filter" = true ]; then
+            # Provide error if no webhook is set and error. Otherwise continue
+            if [ -z "webhook" ]; then
+              echo "NO SLACK WEBHOOK SET"
+              echo "Please input your SLACK_WEBHOOK value either in the settings for this project, or as a parameter for this orb."
+              exit 1
+            else
+              #Create Members string
+              if [ -n "" ]; then
+                IFS="," read -ra SLACK_MEMBERS <<< ""
+                for i in "${SLACK_MEMBERS[@]}"; do
+                  if [ $(echo ${i} | head -c 1) == "S" ]; then
+                    SLACK_MENTIONS="${SLACK_MENTIONS}<!subteam^${i}> "
+                  elif echo ${i} | grep -E "^(here|channel|everyone)$" > /dev/null; then
+                    SLACK_MENTIONS="${SLACK_MENTIONS}<!${i}> "
+                  else
+                    SLACK_MENTIONS="${SLACK_MENTIONS}<@${i}> "
+                  fi
+                done
+              fi
+              #If successful
+              if [ "$SLACK_BUILD_STATUS" = "success" ]; then
+                #Skip if fail_only
+                if [ true = true ]; then
+                  echo "The job completed successfully"
+                  echo '"fail_only" is set to "true". No Slack notification sent.'
+                else
+                  curl -X POST -H 'Content-type: application/json' \
+                    --data "{ \
+                              \"attachments\": [ \
+                                { \
+                                  \"fallback\": \":tada: A $CIRCLE_JOB job has succeeded!\", \
+                                  \"text\": \":tada: A $CIRCLE_JOB job has succeeded! $SLACK_MENTIONS\", \
+                                  \"fields\": [ \
+                                    { \
+                                      \"title\": \"Project\", \
+                                      \"value\": \"$CIRCLE_PROJECT_REPONAME\", \
+                                      \"short\": true \
+                                    }, \
+                                    { \
+                                      \"title\": \"Job Number\", \
+                                      \"value\": \"$CIRCLE_BUILD_NUM\", \
+                                      \"short\": true \
+                                    } \
+                                  ], \
+                                  \"actions\": [ \
+                                    { \
+                                      \"type\": \"button\", \
+                                      \"text\": \"Visit Job\", \
+                                      \"url\": \"$CIRCLE_BUILD_URL\" \
+                                    } \
+                                  ], \
+                                  \"color\": \"#1CBF43\" \
+                                } \
+                              ] \
+                            } " webhook
+                  echo "Job completed successfully. Alert sent."
+                fi
+              else
+                #If Failed
+                curl -X POST -H 'Content-type: application/json' \
+                  --data "{ \
+                    \"attachments\": [ \
+                      { \
+                        \"fallback\": \":red_circle: A $CIRCLE_JOB job has failed!\", \
+                        \"text\": \":red_circle: A $CIRCLE_JOB job has failed! $SLACK_MENTIONS\", \
+                        \"fields\": [ \
+                          { \
+                            \"title\": \"Project\", \
+                            \"value\": \"$CIRCLE_PROJECT_REPONAME\", \
+                            \"short\": true \
+                          }, \
+                          { \
+                            \"title\": \"Job Number\", \
+                            \"value\": \"$CIRCLE_BUILD_NUM\", \
+                            \"short\": true \
+                          } \
+                        ], \
+                        \"actions\": [ \
+                          { \
+                            \"type\": \"button\", \
+                            \"text\": \"Visit Job\", \
+                            \"url\": \"$CIRCLE_BUILD_URL\" \
+                          } \
+                        ], \
+                        \"color\": \"#ed5c5c\" \
+                      } \
+                    ] \
+                  } " webhook
+                echo "Job failed. Alert sent."
+              fi
+            fi
+          else
+            echo "Current branch is not included in only_for_branches filter; no status alert will be sent"
+          fi
+        name: Slack - Sending Status Alert
+        shell: /bin/bash
+        when: always
   algolia-index:
     docker:
     - image: docker.mirror.hashicorp.services/node:12
@@ -1052,6 +1350,16 @@ jobs:
     working_directory: ~/boundary
     steps:
     - checkout
+    - run:
+        command: |
+          make install-go
+          source ~/.bashrc
+          echo 'export GOROOT=$GOROOT' >> "$BASH_ENV"
+          echo 'export GOPATH=$GOPATH' >> "$BASH_ENV"
+          echo 'export PATH=$PATH' >> "$BASH_ENV"
+          echo "$ go version"
+          go version
+        name: Install go
     - run:
         command: |
           which pg_isready || sudo apt-get update && sudo apt-get install -y postgresql-client
@@ -1650,6 +1958,8 @@ workflows:
   ci:
     jobs:
     - build
+    - test-api
+    - test-sdk
     - test-sql-latest
     - test-sql-11-alpine
     - test-sql-12-alpine
